In [1]:
from pathlib import Path
import numpy as np
from pprint import pprint

from skellymodels.experimental.model_redo.managers.human import Human, HumanAspectNames

Input the path to raw 3D data file (as would come out of SkellyForge) 

In [2]:
path_to_data = Path(r"C:\Users\aaron\freemocap_data\recording_sessions\freemocap_test_data\output_data\raw_data\mediapipe_3dData_numFrames_numTrackedPoints_spatialXYZ.npy")
data = np.load(path_to_data)


This is the new model info that's loaded from the YAML. Take a look  the model info at some point. It's very much in prototype.

In [3]:
from skellymodels.experimental.model_redo.tracker_info.model_info import MediapipeModelInfo
model_info = MediapipeModelInfo()

This is all you need to create a Human model. There's no data loaded in the model itself yet, but it has all the proper structures (tracked points/virtual points/all the anatomical definitions) that we currently have in the model data loaded for each aspect. 

In [4]:
human = Human(
            name="human_one", 
            model_info=model_info
            )
pprint([human.aspects])


[{'body': Aspect: body
  Anatomical Structure:
  33 tracked points
  4 virtual markers
  22 segments
  14 center of mass definitions
  16 joint hierarchies
  Trajectories: No trajectories
  Error: No reprojection error
  Metadata: : {'tracker_type': 'mediapipe'}

,
  'face': Aspect: face
  Anatomical Structure:
  478 tracked points
  No virtual markers
  No segment connections
  No center of mass definitions
  No joint hierarchy
  Trajectories: No trajectories
  Error: No reprojection error
  Metadata: : {'tracker_type': 'mediapipe'}

,
  'left_hand': Aspect: left_hand
  Anatomical Structure:
  21 tracked points
  No virtual markers
  No segment connections
  No center of mass definitions
  No joint hierarchy
  Trajectories: No trajectories
  Error: No reprojection error
  Metadata: : {'tracker_type': 'mediapipe'}

,
  'right_hand': Aspect: right_hand
  Anatomical Structure:
  21 tracked points
  No virtual markers
  No segment connections
  No center of mass definitions
  No joint hie

For the Human class, the aspects are already set (body/left hand/right hand/face) and you can access them as properties of the class

In [5]:
#For example if you want to access the marker names for an aspect, you could do what's shown below (We could make this easier to access down the line, if we feel the need)
print(f"Body marker names: {human.body.anatomical_structure.marker_names}")
print(f"Left hand marker names: {human.left_hand.anatomical_structure.marker_names}")


Body marker names: ['nose', 'left_eye_inner', 'left_eye', 'left_eye_outer', 'right_eye_inner', 'right_eye', 'right_eye_outer', 'left_ear', 'right_ear', 'mouth_left', 'mouth_right', 'left_shoulder', 'right_shoulder', 'left_elbow', 'right_elbow', 'left_wrist', 'right_wrist', 'left_pinky', 'right_pinky', 'left_index', 'right_index', 'left_thumb', 'right_thumb', 'left_hip', 'right_hip', 'left_knee', 'right_knee', 'left_ankle', 'right_ankle', 'left_heel', 'right_heel', 'left_foot_index', 'right_foot_index', 'head_center', 'neck_center', 'trunk_center', 'hips_center']
Left hand marker names: ['wrist', 'thumb_cmc', 'thumb_mcp', 'thumb_ip', 'thumb_tip', 'index_finger_mcp', 'index_finger_pip', 'index_finger_dip', 'index_finger_tip', 'middle_finger_mcp', 'middle_finger_pip', 'middle_finger_dip', 'middle_finger_tip', 'ring_finger_mcp', 'ring_finger_pip', 'ring_finger_dip', 'ring_finger_tip', 'pinky_mcp', 'pinky_pip', 'pinky_dip', 'pinky_tip']


To add data from a numpy, use the `add_tracked_points_numpy` function, which splits up the data according to the information defined in the model info. There is also a `from_tracked_points_numpy` class method that creates the Human class and adds data from numpy in 1 function.
Note that now in the printed aspect below, you can see a new trajectory `3d_xyz` added. The reason I called it `3d_xyz` is because that's the name that gets tagged to that Trajectory when saving out the file later.

In [6]:
human.add_tracked_points_numpy(tracked_points_numpy_array=data)
pprint([human.body])

Calculating virtual markers: ['head_center', 'neck_center', 'trunk_center', 'hips_center']
[Aspect: body
  Anatomical Structure:
  33 tracked points
  4 virtual markers
  22 segments
  14 center of mass definitions
  16 joint hierarchies
  Trajectories: 1 trajectories: ['3d_xyz']
  Error: No reprojection error
  Metadata: : {'tracker_type': 'mediapipe'}

]


Here's how you can currently access the data. I think it's a little unwieldy and could be easier - but that's something to look at later. Below that you can also see how to get your data both as a numpy array and a pandas dataframe. 

In [7]:
print(human.body.trajectories['3d_xyz'].data)

{'nose': array([[ -577.20118632, -1180.41480985,  1851.72117414],
       [ -529.13430666, -1090.42079195,  1733.34523614],
       [ -441.88111942, -1009.54973053,  1570.97898542],
       [ -395.71807517,  -963.00623884,  1482.6350931 ],
       [ -385.39166434,  -949.61871024,  1452.91946994],
       [ -398.46902352,  -956.82901384,  1458.78309648],
       [ -413.7789136 ,  -955.39114333,  1469.22935954],
       [ -410.35744945,  -947.7990604 ,  1459.16637948],
       [ -400.61252035,  -942.18088396,  1444.88763198],
       [ -390.3448354 ,  -941.67910754,  1436.16681622],
       [ -389.9551229 ,  -947.28615975,  1437.41009378],
       [ -391.70230426,  -959.0702294 ,  1443.43718176],
       [ -398.46548075,  -972.02333143,  1454.48802113],
       [ -411.60650954,  -974.21461129,  1456.64020176],
       [ -417.52447455,  -973.42304077,  1457.39382835],
       [ -417.69800444,  -972.57760164,  1456.90471401],
       [ -414.60100297,  -969.32414402,  1453.03582801],
       [ -408.4449    

In [8]:
print(f"Data as numpy: {human.body.trajectories['3d_xyz'].as_numpy}")

Data as numpy: [[[ -577.20118632 -1180.41480985  1851.72117414]
  [ -567.96077655 -1199.17746544  1790.95603386]
  [ -554.52165965 -1183.67306463  1775.5186155 ]
  ...
  [ -567.21365342  -846.59579601  1860.83320506]
  [ -558.58092572  -569.42988663  2015.3545526 ]
  [ -549.94819802  -292.26397724  2169.87590015]]

 [[ -529.13430666 -1090.42079195  1733.34523614]
  [ -515.34979626 -1102.79892207  1680.55895397]
  [ -504.9398324  -1091.59615118  1670.0232309 ]
  ...
  [ -474.82905021  -759.22925173  1701.01911218]
  [ -479.2365953   -491.64708885  1881.50661433]
  [ -483.64414038  -224.06492597  2061.99411648]]

 [[ -441.88111942 -1009.54973053  1570.97898542]
  [ -423.02015592 -1015.94648718  1523.30160058]
  [ -413.18460929 -1005.01256476  1514.18441946]
  ...
  [ -396.86437422  -706.46207707  1558.78307222]
  [ -405.31193482  -455.38949608  1750.4840884 ]
  [ -413.75949542  -204.31691509  1942.18510458]]

 ...

 [[           nan            nan            nan]
  [           nan       

In [9]:
print(f"Data as dataframe:\n {human.body.trajectories['3d_xyz'].as_dataframe}")

Data as dataframe:
       frame          keypoint           x            y            z
0         0              nose -577.201186 -1180.414810  1851.721174
1         0    left_eye_inner -567.960777 -1199.177465  1790.956034
2         0          left_eye -554.521660 -1183.673065  1775.518615
3         0    left_eye_outer -541.809449 -1167.776933  1760.177319
4         0   right_eye_inner -604.460672 -1219.303703  1811.391632
...     ...               ...         ...          ...          ...
8209    221  right_foot_index         NaN          NaN          NaN
8210    221       head_center         NaN          NaN          NaN
8211    221       neck_center         NaN          NaN          NaN
8212    221      trunk_center         NaN          NaN          NaN
8213    221       hips_center         NaN          NaN          NaN

[8214 rows x 5 columns]


There's also some basic methods that I wrote into the Actor class that you can use to get marker or frame data. Those are demonstrated below.

While I think the way it's written is necessary for the Actor class, where we don't have a strong sense of what might be added to it, I don't think this method is ideal for the Human class. Too many strings involved. So it would probably be worth giving the human class additional methods to do the below functions.

In [10]:
print(human.get_marker_data(aspect_name=HumanAspectNames.BODY.value, type = '3d_xyz', marker_name= 'left_heel'))
print(human.get_frame(aspect_name=HumanAspectNames.BODY.value, type = '3d_xyz', frame_number=100))

[[-441.99804627  496.93359457 2591.20431137]
 [-343.09804061  526.36281038 2303.01124462]
 [-349.94504003  524.23443059 2260.45653215]
 [-342.86562284  514.42812677 2209.2608599 ]
 [-346.05965329  489.52906445 2177.91703208]
 [-355.88150734  489.3879822  2170.07513279]
 [-350.9086024   503.86889906 2171.53447665]
 [-317.35376382  582.67487458 2233.87480559]
 [-310.27367781  597.05092575 2245.45054716]
 [-310.79751312  604.85968182 2247.73781791]
 [-306.2433391   603.83737023 2255.99937688]
 [-308.04285589  610.64329434 2258.78066992]
 [-311.1223321   609.15053361 2259.04174545]
 [-311.8636477   611.30991974 2259.19521589]
 [-309.14622832  613.23461231 2261.64366807]
 [-309.16745502  616.14447237 2260.91645298]
 [-312.14710798  612.97804781 2258.67605321]
 [-313.14318151  612.66007965 2259.95277126]
 [-313.70711965  613.20839975 2258.78939261]
 [-314.45897802  615.7814531  2262.48647634]
 [-314.99154349  615.47488211 2263.01757781]
 [-313.92303838  615.17313554 2266.91688898]
 [-317.372

To add reprojection error to the 3d data, first load it from the raw data folder

In [11]:
reprojection_error_path = Path(r"/Users/philipqueen/freemocap_data/recording_sessions/freemocap_sample_data/output_data/raw_data/mediapipe_3dData_numFrames_numTrackedPoints_reprojectionError.npy")
reprojection_error_data = np.load(reprojection_error_path)

FileNotFoundError: [Errno 2] No such file or directory: '\\Users\\philipqueen\\freemocap_data\\recording_sessions\\freemocap_sample_data\\output_data\\raw_data\\mediapipe_3dData_numFrames_numTrackedPoints_reprojectionError.npy'

In [12]:
reprojection_error_data.shape

(1108, 553)

We can add the reprojection error from a numpy array using `add_reprojection_error_numpy`, the same way we did from `tracked_points`.

In [13]:
human.add_reprojection_error_numpy(reprojection_error_data=reprojection_error_data)

Now we can get the error data by frame or marker

In [14]:
print(human.get_error_marker(aspect_name=HumanAspectNames.BODY.value, marker_name= 'left_heel'))
print(human.get_error_frame(aspect_name=HumanAspectNames.BODY.value, frame_number=100))

[25.52732232 17.65498045 13.86470385 ...         nan         nan
         nan]
{'nose': 5.746020473415346, 'left_eye_inner': 5.90244210284299, 'left_eye': 5.813339899127283, 'left_eye_outer': 5.656964136384929, 'right_eye_inner': 6.838173316247693, 'right_eye': 7.303391546297601, 'right_eye_outer': 7.579633577886159, 'left_ear': 5.395652581201134, 'right_ear': 6.981296190908798, 'mouth_left': 5.73569256588852, 'mouth_right': 6.010359255994679, 'left_shoulder': 10.209152768874075, 'right_shoulder': 7.507343032311457, 'left_elbow': 15.799318229136006, 'right_elbow': 22.819596236039697, 'left_wrist': 20.216664636915368, 'right_wrist': 85.12797579441322, 'left_pinky': 19.499122752521046, 'right_pinky': 100.0126877968987, 'left_index': 18.25631177921259, 'right_index': 104.39363726455751, 'left_thumb': 17.114486943363136, 'right_thumb': 97.36284714160382, 'left_hip': 6.980321597510373, 'right_hip': 7.2618867088386025, 'left_knee': 3.2968320942090963, 'right_knee': 12.394759685267323, 'left_

The following functions are what exist in our anatomical pipeline at the moment: calculating center of mass and enforcing rigid bones. For both, after the data is calculated, they get added as Trajectories to the relevant Aspect

In [2]:
from skellymodels.experimental.model_redo.biomechanics.biomechanics_processor import BiomechanicsProcessor

In [15]:
BiomechanicsProcessor.process_human(human)

TypeError: CenterOfMassCalculation.calculate() missing 1 required positional argument: 'self'

In [16]:
for aspect in human.aspects.values():
    aspect.enforce_rigid_bones()

NameError: name 'human' is not defined

Below you can see extra trajectories added to the body after running the above functions

In [17]:
for aspect in human.aspects.values():
    pprint({aspect.name: aspect.trajectories})

{'body': {'3d_xyz': Trajectory with 1108 frames and 37 markers,
          'rigid_3d_xyz': Trajectory with 1108 frames and 37 markers,
          'segment_com': Trajectory with 1108 frames and 14 markers,
          'total_body_com': Trajectory with 1108 frames and 1 markers}}
{'face': {'3d_xyz': Trajectory with 1108 frames and 478 markers}}
{'left_hand': {'3d_xyz': Trajectory with 1108 frames and 21 markers}}
{'right_hand': {'3d_xyz': Trajectory with 1108 frames and 21 markers}}


Each saving function is a method in the Actor baseclass. They leverage the `as_numpy` and `as_dataframe` properties that each Trajectory has. We basically iterate over each Trajectory in an Aspect, and save it out, using the metadata stored within each aspect/trajectory to dynamically build the file names. The last function builds the 'big' CSV we have with all the data.

And these three functions are all we need to save out similar/almost equivalent data to what we currently save out for freemocap in the output data folder

In [18]:
human.save_out_numpy_data()
human.save_out_csv_data()
human.save_out_all_data_csv()
human.save_out_all_data_parquet()


Saving out numpy: mediapipe body 3d_xyz
Saving out numpy: mediapipe body total_body_com
Saving out numpy: mediapipe body segment_com
Saving out numpy: mediapipe body rigid_3d_xyz
Saving out numpy: mediapipe face 3d_xyz
Saving out numpy: mediapipe left_hand 3d_xyz
Saving out numpy: mediapipe right_hand 3d_xyz
Saving out CSV: mediapipe body 3d_xyz
Saving out CSV: mediapipe body total_body_com
Saving out CSV: mediapipe body segment_com
Saving out CSV: mediapipe body rigid_3d_xyz
Saving out CSV: mediapipe face 3d_xyz
Saving out CSV: mediapipe left_hand 3d_xyz
Saving out CSV: mediapipe right_hand 3d_xyz
Data successfully saved to 'freemocap_data_by_frame.csv'
Data successfully saved to 'freemocap_data_by_frame.parquet'
Loaded DataFrame:
        frame         keypoint           x           y            z  \
0           0             nose -681.293594 -802.250349  1262.992698   
1           0   left_eye_inner -650.571509 -827.688951  1242.464173   
2           0         left_eye -634.755223 -8

To view parquet metadata, load it as a dataframe and access the attrs:

In [19]:
import pandas as pd
loaded_df = pd.read_parquet('freemocap_data_by_frame.parquet')
print("Loaded DataFrame:")
print(loaded_df)
print("Metadata:", loaded_df.attrs['metadata'])

Loaded DataFrame:
        frame         keypoint           x           y            z  \
0           0             nose -681.293594 -802.250349  1262.992698   
1           0   left_eye_inner -650.571509 -827.688951  1242.464173   
2           0         left_eye -634.755223 -821.343474  1241.898784   
3           0   left_eye_outer -619.470784 -813.919184  1240.230723   
4           0  right_eye_inner -680.327949 -843.743989  1251.791717   
...       ...              ...         ...         ...          ...   
617151   1107  ring_finger_tip         NaN         NaN          NaN   
617152   1107        pinky_mcp         NaN         NaN          NaN   
617153   1107        pinky_pip         NaN         NaN          NaN   
617154   1107        pinky_dip         NaN         NaN          NaN   
617155   1107        pinky_tip         NaN         NaN          NaN   

                       model  reprojection_error  
0             mediapipe_body           16.816206  
1             mediapipe_bod